chore: fix port, remove port on doc URLs
CodeForAfrica/backend pull request #4
Opened 2024-07-16 06:46 UTC by VinneyJ

1. change port from 8082 to 80
2. changed domain from mediacloud.org to civicsignal.africa and removed 8082 port from in docs URLs,

2024-07-16 07:05 UTC, thepsalmist commented on doc/api_2_0_spec/admin_api_2_0_spec.md
> +URL: https://aapp.civicsignal.africag/api/v2/stories/list?last_processed_stories_id=8625915
```suggestion
URL: https://app.civicsignal.africag/api/v2/stories/list?last_processed_stories_id=8625915
```

2024-07-16 07:05 UTC, thepsalmist commented on doc/api_2_0_spec/api_2_0_spec.md
> +URL: <https://app.mcivicsignal.africa/api/v2/auth/activate>
```suggestion
URL: <https://app.civicsignal.africa/api/v2/auth/activate>
```

2024-07-16 07:05 UTC, thepsalmist commented on doc/api_2_0_spec/api_2_0_spec.md
> +URL: https://app.civicsignal.africa:80/api/v2/media/single/1
```suggestion
URL: https://app.civicsignal.africa/api/v2/media/single/1
```

2024-07-16 08:13 UTC, DavidTheProgrammer commented on doc/api_2_0_spec/api_2_0_spec.md
> +URL: https://app.mcivicsignal.africa/api/v2/stats/list
https://app.civicsignal.africa/api/v2/stats/list

2024-07-16 08:17 UTC, satoru260 commented on doc/api_2_0_spec/api_2_0_spec.md
> +URL: https://app.mcivicsignal.africa/api/v2/stats/list
```suggestion
URL: https://app.civicsignal.africa/api/v2/stats/list
```

2024-07-16 08:20 UTC, DavidTheProgrammer requested changes
LGTM aside from the typos

2024-07-17 12:16 UTC, thepsalmist reviewed
LGTM

2024-07-17 12:16 UTC, thepsalmist commented on doc/api_2_0_spec/admin_api_2_0_spec.md
> +URL: https://app.civicsignal.africa/aip/v2/stories/put_tags
```suggestion
URL: https://app.civicsignal.africa/api/v2/stories/put_tags
```

2024-07-18 07:52 UTC, thepsalmist approved these changes

2024-07-18 08:13 UTC, kilemensi reviewed
👍🏽 .. don't have full context so if @thepsalmist is happy with it, please proceed to merge

---

1. Why is the **API** backend called `app`? Shouldn't it be `api.civicsignal.africa` instead of `app.civicsignal.africa`? `app.hostname` is usually a frontend/UI app e.g. https://app.gitbook.com, https://app.sendgrid.com/, etc.
2. Lets fix or remove the GitHub actions (Not in this PR)
<img width="1255" alt="Screenshot 2024-07-18 at 11 06 42" src="https://github.com/user-attachments/assets/9c2dbf9e-7f27-45b9-84b2-0843bf5d5446">

2024-07-18 08:13 UTC, kilemensi commented on doc/api_2_0_spec/admin_api_2_0_spec.md
> +URL: https://aapp.civicsignal.africag/api/v2/stories/list?last_processed_stories_id=8625915
```suggestion
URL: https://app.civicsignal.africag/api/v2/stories/list?last_processed_stories_id=8625915
```

2024-07-18 08:13 UTC, kilemensi commented on doc/api_2_0_spec/admin_api_2_0_spec.md
> +https:///api/v2/tags/create
Don't have full context but doesn't this need a hostname?

2024-07-19 07:00 UTC, thepsalmist commented
> 👍🏽 .. don't have full context so if @thepsalmist is happy with it, please proceed to merge
> 
> 1. Why is the **API** backend called `app`? Shouldn't it be `api.civicsignal.africa` instead of `app.civicsignal.africa`? `app.hostname` is usually a frontend/UI app e.g. https://app.gitbook.com, https://app.sendgrid.com/, etc.
> 2. Lets fix or remove the GitHub actions (Not in this PR)
> 
> <img alt="Screenshot 2024-07-18 at 11 06 42" width="1255" src="https://private-user-images.githubusercontent.com/1779590/349873252-9c2dbf9e-7f27-45b9-84b2-0843bf5d5446.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzI2NTAsIm5iZiI6MTcyMTM3MjM1MCwicGF0aCI6Ii8xNzc5NTkwLzM0OTg3MzI1Mi05YzJkYmY5ZS03ZjI3LTQ1YjktODRiMi0wODQzYmY1ZDU0NDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTlUMDY1OTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjMwNzk2OTRmNDdjNDYyMmYzODU3OGI5ZmYwZDRiMDM3OTE4YzdhYTI3YjM5OTY4YjYyZWE5MDQyOTVjMzZiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0j7F6btOd9hCLs_MYcRLvD6ClLfgMa3tInLKelp_Nd0">

I'm happy with making the domain changes to reflect this is an `api` and not `app` and make corresponding changes to the frontend applications

2024-07-19 08:05 UTC, VinneyJ commented
Cool on it.

2024-07-19 09:06 UTC, DavidTheProgrammer approved these changes
LGTM

2024-07-19 09:12 UTC, merged